### ISSUE TITLE
How to contribute on LXD-UI development? 

### ISSUE THREAD

**Issue by xlmnxp** [canonical/lxd-ui#105]
Hello,
I'm JavaScript+TypeScript Developer and I have knowledge of LXD and how it work and it's Rest APIs,
I saw this project and I want to help on develop it but I didn't find any roadmap or project tickets/cards todo

Is there a way to contribute?

**Comment by edlerd** [comment]
Hello @xlmnxp,

Thank you for expressing interest in our project. We appreciate your enthusiasm and willingness to contribute.

One way you could help is by building a storage list similar to the one at https://github.com/canonical/lxd-ui/blob/main/static/js/NetworkList.tsx. We use https://tanstack.com/query/v4 for data fetching, so you would need to create a new file for storage in https://github.com/canonical/lxd-ui/tree/main/static/js/api that could be used by a StorageList component.

Once you have completed the storage list, you could consider advancing the storage management with features such as creation and deletion. We encourage you to review the existing instance and profile management in order to make your implementation consistent with the rest of the project. While these features are currently being worked on, the main interaction patterns are likely to remain the same.

Thank you again for your interest and support. We look forward to seeing your contribution to the project.

**Comment by xlmnxp** [comment]
> Hello @xlmnxp,
> 
> Thank you for expressing interest in our project. We appreciate your enthusiasm and willingness to contribute.
> 
> One way you could help is by building a storage list similar to the one at https://github.com/canonical/lxd-ui/blob/main/static/js/NetworkList.tsx. We use https://tanstack.com/query/v4 for data fetching, so you would need to create a new file for storage in https://github.com/canonical/lxd-ui/tree/main/static/js/api that could be used by a StorageList component.
> 
> Once you have completed the storage list, you could consider advancing the storage management with features such as creation and deletion. We encourage you to review the existing instance and profile management in order to make your implementation consistent with the rest of the project. While these features are currently being worked on, the main interaction patterns are likely to remain the same.
> 
> Thank you again for your interest and support. We look forward to seeing your contribution to the project.

got it, also I can use the following Swagger to explore LXD APIs:
https://linuxcontainers.org/lxd/api/master/#/
