### ISSUE TITLE
Foreing language keyboards not working fully in console

### ISSUE THREAD

**Issue by friki67** [canonical/lxd-ui#348]
Hello. I've been trying the Spanish keyboard in an Ubuntu and OpenSuse VMs and there are keys that do not correspond with the layout, i.e: 
Ñ - 'º'
< - '-'
Same for both VMs after selecting Spanish (Spain) keyboard and rebooting (just in case).

Regards.
PS: Alt Gr key is not working in Chrome, it says "no map for 225" so no special characters (like @ or # for my spanish keyboard) can be used.

**Comment by lorumic** [comment]
Thanks for reporting this. This brings to light a limitation of the underlying spice-html5 library that we use to display the VGA console in the browser - which is an incomplete mapping of the browser key codes with the keyboard scan codes transmitted by Spice. This explains why hitting the AltGr key shows you that message. There is no mapping in the library for key code 225.
Moreover, this library also lacks support for international keyboard layouts.
We'll investigate how to tackle this problem, but it might take some time. I'll add the Bug label for the time being.

**Comment by lorumic** [comment]
Hi @friki67. I wanted to add a follow-up on this issue. Due to the aforementioned limitations in the spice-html5 library, it will not be an easy fix, and for sure not a quick one. But above all, since there is this translation of the browser's key codes to be done "in the middle", for sure we will not be able to respect the keyboard layout that is set in the guest VM - we cannot retrieve such information from the web UI.

So, for the time being, what I can suggest you here is to either [invoke the VGA console from the CLI](https://linuxcontainers.org/lxd/docs/latest/howto/instances_console/#access-the-graphical-console-for-virtual-machines) - which will work and also respect the keyboard layout that you set in the VM - or, if your use case is the terminal, you can use the terminal tab in the web UI and you will have the correct key mappings there, hence being able to use the special characters that you mentioned. Please bear in mind that also in this case, again due to the fact that there is the browser in the middle, the host keyboard layout will be used, not the guest one.

Sorry that I cannot bring you better news than this.

**Comment by friki67** [comment]
Hello!. Just to tell you about the deprecation in RHL9 and derivatives (Almalinux, Rocky linux) of the Spice libraries, so you cannot use the VGA console in any of these OSs, AFAIK. See my post here https://discourse.ubuntu.com/t/lxc-console-vga-error/37389/4
Regards

**Comment by edlerd** [comment]
Hello again, we have a fix ready. It is a bit too late to be included in LXD 5.20, but the next release will include this.
