### ISSUE TITLE
How to deploy for a cluster?

### ISSUE THREAD

**Issue by KarmaPoliceT2** [canonical/lxd-ui#478]
How should I think about the lxd-ui capability when deploying an LXD cluster?

1. Should each LXD host have its own lxd-ui running and then I enable some kind of load balancer in front of them to consolidate to a single IP/domain?
2. Should only one LXD host have the lxd-ui running? but then what if that host goes offline for patching or other... 
3. Should the lxd-ui be run on some other HA solution (e.g. a separate web cluster) and "pointed at" all three lxd-hosts?

Just trying to figure out the best architecture to provide the web-ui in an HA way. Thx!

**Comment by edlerd** [comment]
Thank you for your request.

You can query any cluster member for the same UI. The UI will show the whole cluster state and also list the nodes and allows to manage cluster groups to target the location of new new instances.

For HA you could have a proxy in front that forwards to the UI of any available member, because each UI will be the same. I think this is a common setup, though the proxy becomes a single point of failure for the UI when there is only one proxy node.

You can do manual HA failover by talking directly to one of the cluster members UI. And if that goes down just talk to another one.

Definitely not 3.

Thinking of it, the best solution would probably be a failover IP that gets routed to any members UI. If a member goes offline the IP is automatically routed to another online member.

Hope this helps, let me know if you have further questions.

**Comment by KarmaPoliceT2** [comment]
Thanks for the insight, definitely makes sense now, a VIP feels like the best way as you mentioned.
